In [ ]:
import numpy as np

def sigmoid(x):
	return 1.0/(1.0 + np.exp(-x))

def sigmoid_der(x):
	return x*(1.0 - x)

In [29]:
class NN:
    def __init__(self, inputs):
        self.inputs = inputs
        self.l=len(self.inputs)
        self.li=len(self.inputs[0])

        self.wi=np.random.random((self.li, self.l))# Generates the matrix of 2 by 4,, input weights
        self.wh=np.random.random((self.l, 1)) #Generates the matrix of 4 by 1

    def think(self, inp): #Logistic regression function
        s1=sigmoid(np.dot(inp, self.wi))
        s2=sigmoid(np.dot(s1, self.wh))
        return s2

    def train(self, inputs,outputs, it):
        for i in range(it):
            l0=inputs
            l1=sigmoid(np.dot(l0, self.wi))
            l2=sigmoid(np.dot(l1, self.wh))

            l2_err=outputs - l2
            l2_delta = np.multiply(l2_err, sigmoid_der(l2))

            l1_err=np.dot(l2_delta, self.wh.T)
            l1_delta=np.multiply(l1_err, sigmoid_der(l1))

            self.wh+=np.dot(l1.T, l2_delta)
            self.wi+=np.dot(l0.T, l1_delta)

inputs=np.array([[0,0], [0,1], [1,0], [1,1] ])
outputs=np.array([ [0], [1],[1], [0]])

n=NN(inputs)
print(n.think(inputs))
n.train(inputs, outputs, 10000)
print(n.think(inputs))

[[0.65780421]
 [0.69954968]
 [0.69777479]
 [0.72956564]]
[[0.01545642]
 [0.98429341]
 [0.98470105]
 [0.01545108]]


In [37]:
inputs=np.array([[0,0], [0,1], [1,0], [1,1] ])
print('li:',len(inputs[0]))
print("..............................")
print('l:',len(inputs))
print("..............................")
print(np.random.random((2,4)))
print("..............................")
print(np.random.random((4,1)))

li: 2
..............................
l: 4
..............................
[[0.99933898 0.15982087 0.41068694 0.87505929]
 [0.42090596 0.96625639 0.58433543 0.66052109]]
..............................
[[0.27473302]
 [0.04150333]
 [0.91694636]
 [0.95062105]]


In [42]:
s1=sigmoid(np.dot([[1,2],[2,3],[3,2],[4,3]], len(inputs) ))
s1

array([[0.98201379, 0.99966465],
       [0.99966465, 0.99999386],
       [0.99999386, 0.99966465],
       [0.99999989, 0.99999386]])

In [40]:
s2=sigmoid(np.dot(s1, ))

array([[0.98201379, 0.99966465],
       [0.99966465, 0.99999386],
       [0.99999386, 0.99966465],
       [0.99999989, 0.99999386]])